module.exports = {
  plugins: ['jsdoc'],
  rules: {
    // https://github.com/gajus/eslint-plugin-jsdoc#check-param-names
    // 関数引数と@param名が一致かどうか
    'jsdoc/check-param-names': 2,
    // https://github.com/gajus/eslint-plugin-jsdoc#eslint-plugin-jsdoc-rules-check-tag-names
    // 無効なブロックタグ名かどうか
    'jsdoc/check-tag-names': 2,
    // https://github.com/gajus/eslint-plugin-jsdoc#check-types
    // 無効なタイプかどうか
    'jsdoc/check-types': 2,
    // https://github.com/gajus/eslint-plugin-jsdoc#no-undefined-types
    'jsdoc/no-undefined-types': 2,
    // https://github.com/gajus/eslint-plugin-jsdoc#require-description
    // 説明文を必須とする
    'jsdoc/require-description': 2,
    // https://github.com/gajus/eslint-plugin-jsdoc#require-hyphen-before-param-description
    // @paramの説明の前にハイフン必須
    'jsdoc/require-hyphen-before-param-description': 2,
    // https://github.com/gajus/eslint-plugin-jsdoc#require-param
    // @param必須
    'jsdoc/require-param': 2,
    // https://github.com/gajus/eslint-plugin-jsdoc#require-param-description
    // @paramの説明必須
    'jsdoc/require-param-description': 2,
    // https://github.com/gajus/eslint-plugin-jsdoc#require-param-name
    // @paramすべてに名前必須
    'jsdoc/require-param-name': 2,
    // https://github.com/gajus/eslint-plugin-jsdoc#require-param-type
    // @paramすべてにtype必須
    'jsdoc/require-param-type': 0,
    // https://github.com/gajus/eslint-plugin-jsdoc#require-returns
    // @returns必須
    'jsdoc/require-returns': 0,
    // https://github.com/gajus/eslint-plugin-jsdoc#require-returns-check
    // @returnsの確認
    'jsdoc/require-returns-check': 2,
    // https://github.com/gajus/eslint-plugin-jsdoc#require-returns-description
    // @returnsの説明文必須
    'jsdoc/require-returns-description': 0,
    // https://github.com/gajus/eslint-plugin-jsdoc#require-returns-type
    // @returnsのtype必須
    'jsdoc/require-returns-type': 2,
    // https://github.com/gajus/eslint-plugin-jsdoc#valid-types
    // 型チェック
    'jsdoc/valid-types': 2,
  },
};
